module.exports = {
    extends: ['./index.js', 'eslint:recommended'],
    rules: {
        'array-bracket-spacing': 'off',
        'arrow-parens': 'off',
        'arrow-spacing': 'off',
        'block-spacing': 'off',
        'comma-style': 'off',
        'computed-property-spacing': 'off',
        'dot-location': 'off',
        'eol-last': 'off',
        'func-call-spacing': 'off',
        'generator-star-spacing': 'off',
        'jsx-quotes': 'off',
        'key-spacing': 'off',
        'keyword-spacing': 'off',
        'linebreak-style': 'off',
        'new-parens': 'off',
        'newline-per-chained-call': 'off',
        'no-floating-decimal': 'off',
        'no-mixed-spaces-and-tabs': 'off',
        'no-multi-spaces': 'off',
        'no-multiple-empty-lines': 'off',
        'no-trailing-spaces': 'off',
        'no-whitespace-before-property': 'off',
        'object-curly-spacing': 'off',
        'one-var-declaration-per-line': 'off',
        'operator-linebreak': 'off',
        'padded-blocks': 'off',
        'quote-props': 'off',
        'rest-spread-spacing': 'off',
        'semi-spacing': 'off',
        'space-before-blocks': 'off',
        'space-in-parens': 'off',
        'space-unary-ops': 'off',
        'template-curly-spacing': 'off',
        'unicode-bom': 'off',
        'wrap-iife': 'off',
        'wrap-regex': 'off',
        'yield-star-spacing': 'off',
    },
    overrides: [
        {
            files: ['*.test.ts'],
            plugins: ['jest'],
            rules: {
            },
        },
        {
            files: ['*.ts'],
            plugins: ['eslint-plugin-tsdoc'],
            extends: ['plugin:@typescript-eslint/recommended', 'plugin:@typescript-eslint/eslint-recommended'],
            rules: {
                '@typescript-eslint/brace-style': 'off',
                '@typescript-eslint/comma-dangle': 'off',
                '@typescript-eslint/comma-spacing': 'off',
                '@typescript-eslint/indent': 'off',
                '@typescript-eslint/member-delimiter-style': 'off',
                '@typescript-eslint/no-extra-semi': 'off',
                '@typescript-eslint/semi': 'off',
                '@typescript-eslint/space-before-function-paren': 'off',
                '@typescript-eslint/space-infix-ops': 'off',
                '@typescript-eslint/type-annotation-spacing': 'off',
            },
        },
    ],
};
